Mbarba/tweaks
Ensembl/ensembl-production-imported pull request #64
Opened 2023-02-14 14:57 UTC by MatBarba

Minor tweaks to scripts/pipelines

2023-02-22 11:35 UTC, JAlvarezJarreta requested changes

2023-02-22 11:35 UTC, JAlvarezJarreta commented on scripts/brc4/json_samples_to_redmine_samples.py
> +
License header missing.

2023-02-22 11:35 UTC, JAlvarezJarreta commented on scripts/brc4/json_samples_to_redmine_samples.py
> +            lines.append("\t".join(cols))
Just a suggestion to avoid some repetitive tasks:
```suggestion
        cols = f"{self.component}\t{self.species}\t{self.name}"
        for sample in self.samples:
            lines.append(f"{cols}\t{sample['name']}")
```

2023-02-22 11:35 UTC, JAlvarezJarreta commented on scripts/brc4/json_samples_to_redmine_samples.py
> +    parser.add_argument('--full', action='store_true',
I'm not fond of this term, `full`, as it is not straightforward to me what it is meant to do (I had to read the code in the previous methods to understand its meaning). What about `--verbose`? For the methods, I have no better suggestion, maybe `get_all`?

2023-02-27 12:52 UTC, MatBarba commented on scripts/brc4/json_samples_to_redmine_samples.py
> +    parser.add_argument('--full', action='store_true',
I've made changes to make things clearer

2023-02-27 12:54 UTC, MatBarba commented on scripts/brc4/json_samples_to_redmine_samples.py
> +            lines.append("\t".join(cols))
I prefer to keep the elements in a list form until they are joined (though I made it a bit shorter/cleaner)

2023-02-27 12:57 UTC, MatBarba commented on scripts/brc4/json_samples_to_redmine_samples.py
> +
Done

2023-02-27 13:39 UTC, JAlvarezJarreta approved these changes
Quite like the new names for the parameters :+1:

2023-02-27 13:39 UTC, JAlvarezJarreta commented on scripts/brc4/json_samples_to_redmine_samples.py
> +
"Unfortunately" this is a PEP8 comment:
```suggestion
        description='Convert a sample list from a json file into a sample list for Redmine'
    )
```

2023-02-27 14:17 UTC, merged